"""
Django settings for gam project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y*7n(6^n-&mzww6g(lc!4ff^_p&y5@0$je*k4-6_6)h&4$7@3a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "debug_toolbar",
    "drf_spectacular",
    "rest_framework",
    "django_filters",
    "archive",
    "gam.accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "gam.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gam.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "griddy",
        "USER": os.getenv("PG_USER"),
        "PASSWORD": os.getenv("PG_PASSWORD"),
        "HOST": os.getenv("PG_HOST"),
        "PORT": os.getenv("PG_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT")

GRIDDY_NFL_EMAIL = os.getenv("GRIDDY_NFL_EMAIL")
GRIDDY_NFL_PASSWORD = os.getenv("GRIDDY_NFL_PASSWORD")

# Cloudflare R2 — destination for the batch HLS packaging pipeline (TGF-362,
# ADR-0008). S3-compatible; the endpoint is https://<account>.r2.cloudflarestorage.com.
# Production reads the keys from AWS Secrets Manager, not .env.
R2_BUCKET = os.getenv("R2_BUCKET")
R2_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL")
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")

# Default league source trees the packaging pipeline walks when none are passed
# on the command line. Colon-separated absolute paths (e.g. the four mounts in
# the TGF-337 catalog report).
HLS_SOURCE_ROOTS = [
    p.strip() for p in os.getenv("HLS_SOURCE_ROOTS", "").split(":") if p.strip()
]

# JWT / JWKS authentication — IdP-agnostic class fed from Clerk-named env vars.
# The auth class itself is IdP-agnostic; settings.py is the one place we name the
# IdP. Swap providers by changing these env vars (and the dashboard/secret-store
# that owns them) without touching the auth class.
JWKS_URL = os.getenv("CLERK_JWKS_URL")
JWT_AUDIENCE = os.getenv("CLERK_AUDIENCE")
JWT_ISSUER = os.getenv("CLERK_ISSUER")
JWT_AUTHORIZED_PARTIES = [
    party.strip()
    for party in os.getenv("CLERK_AUTHORIZED_PARTIES", "").split(",")
    if party.strip()
]
# Server-side Clerk Backend API key. Loaded from AWS Secrets Manager in
# deployed envs; .env in dev. Reserved for user-lookup work in TGF-317; not
# used for token verification.
CLERK_SECRET_KEY = os.getenv("CLERK_SECRET_KEY")

# Playback / video delivery (TGF-360, ADR-0008). The origin is environment
# driven so the same code targets a local Worker (e.g. http://localhost:8787)
# during the PoC and a production host later. The signing secret is shared
# with the Worker that fronts R2; rotating it invalidates outstanding URLs.
VIDEO_ORIGIN_URL = os.getenv("VIDEO_ORIGIN_URL", "http://localhost:8787")
PLAYBACK_TOKEN_SECRET = os.getenv("PLAYBACK_TOKEN_SECRET", "")
PLAYBACK_TOKEN_ALGORITHM = os.getenv("PLAYBACK_TOKEN_ALGORITHM", "HS256")
PLAYBACK_TOKEN_ISSUER = os.getenv("PLAYBACK_TOKEN_ISSUER", "griddy-api")
PLAYBACK_TOKEN_AUDIENCE = os.getenv("PLAYBACK_TOKEN_AUDIENCE", "griddy-video-worker")
# Capped at 15 minutes by ``gam.playback.tokens.MAX_TTL_SECONDS``; values
# larger than the cap are silently clamped down to it.
PLAYBACK_TOKEN_TTL_SECONDS = int(os.getenv("PLAYBACK_TOKEN_TTL_SECONDS", "900"))

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration
# https://docs.djangoproject.com/en/6.0/topics/logging/

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {filename}:{lineno} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "gam.log"),
            "when": "midnight",
            "backupCount": 30,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "archive": {
            "handlers": ["console", "file"],
            "level": os.getenv("ARCHIVE_LOG_LEVEL", "DEBUG"),
            "propagate": False,
        },
    },
}


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.CursorPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "gam.auth.jwt.JWKSAuthentication",
        "gam.auth.api_key.APIKeyAuthentication",
    ],
    # "DEFAULT_PERMISSION_CLASSES": [
    #     # TODO: Decide on this
    # ]
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # "DEFAULT_THROTTLE_CLASSES": [],
    # "DEFAULT_THROTTLE_RATES": []
}

SPECTACULAR_SETTINGS = {
    "TITLE": "GAM API",
    "DESCRIPTION": "REST API for the Griddy Archive Manager",
    "VERSION": "0.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
