# Generated by Django 6.0.1 on 2026-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_gamecompleteness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='long_name',
        ),
        migrations.AddField(
            model_name='league',
            name='short_name',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
