# Generated by Django 6.0.1 on 2026-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_rename_name_league_long_name_league_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgunit',
            old_name='name',
            new_name='long_name',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='short_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
