# Generated by Django 6.0.1 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0006_venue_capacity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                fields=("name", "city", "state"), name="uniq_venue_city_state"
            ),
        ),
    ]
