# Generated by Django 6.0.1 on 2026-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0007_venue_uniq_venue_city_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.ImageField(null=True, upload_to="teams/logos/"),
        ),
    ]
