# Generated by Django 6.0.1 on 2026-02-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0008_alter_team_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="week",
            field=models.IntegerField(null=True),
        ),
    ]
