# Generated by Django 6.0.1 on 2026-02-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0010_teamvenueoccupancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamvenueoccupancy",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venue_occupancies",
                to="archive.team",
            ),
        ),
        migrations.AlterField(
            model_name="teamvenueoccupancy",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_occupancies",
                to="archive.venue",
            ),
        ),
    ]
