# Generated by Django 6.0.1 on 2026-02-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_add_related_names_to_teamvenueoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ordinal',
            field=models.IntegerField(null=True),
        ),
    ]
