# Generated by Django 6.0.1 on 2026-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0012_game_ordinal"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="alternate_name",
            field=models.CharField(max_length=140, null=True),
        ),
    ]
