# Generated by Django 6.0.1 on 2026-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0013_team_alternate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="additional_colors",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
    ]
