# Generated by Django 6.0.1 on 2026-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0014_team_additional_colors_team_bonus_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisition",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assettag",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gamecompleteness",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamaffiliation",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamvenueoccupancy",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="videoasset",
            name="bonus_data",
            field=models.JSONField(
                help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                null=True,
            ),
        ),
    ]
