# Generated by Django 6.0.1 on 2026-02-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0015_acquisition_bonus_data_assettag_bonus_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="country",
            field=models.CharField(default="US", max_length=60),
        ),
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.CharField(default="US", max_length=60),
        ),
        migrations.AlterField(
            model_name="venue",
            name="country",
            field=models.CharField(default="US", max_length=60),
        ),
    ]
