# Generated by Django 6.0.1 on 2026-02-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0016_alter_league_country_alter_team_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisition",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="assettag",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gamecompleteness",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="league",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="season",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="source",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tag",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="teamaffiliation",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="teamvenueoccupancy",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="venue",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="videoasset",
            name="external_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
