# Generated by Django 6.0.1 on 2026-02-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0017_acquisition_external_ids_assettag_external_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="state",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
    ]
