# Generated by Django 6.0.1 on 2026-02-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0018_alter_team_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="state",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
    ]
