# Generated by Django 6.0.1 on 2026-02-09 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0019_alter_venue_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="broadcast_channel",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="game",
            name="kickoff_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.CreateModel(
            name="ExtraPointsBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("attempts", models.IntegerField(default=0)),
                ("made", models.IntegerField(default=0)),
                ("blocked", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FieldGoalsBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("attempts", models.IntegerField(default=0)),
                ("made", models.IntegerField(default=0)),
                ("blocked", models.IntegerField(default=0)),
                ("yards", models.IntegerField(default=0)),
                ("avg_yards", models.FloatField(blank=True, null=True)),
                ("longest", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FumblesBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("fumbles", models.IntegerField(default=0)),
                ("own_recoveries", models.IntegerField(default=0)),
                ("own_recovery_yards", models.IntegerField(default=0)),
                ("own_recovery_tds", models.IntegerField(default=0)),
                ("opp_recoveries", models.IntegerField(default=0)),
                ("opp_recovery_yards", models.IntegerField(default=0)),
                ("opp_recovery_tds", models.IntegerField(default=0)),
                ("forced_fumbles", models.IntegerField(default=0)),
                ("out_of_bounds", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KickingBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("kickoffs", models.IntegerField(default=0)),
                ("yards", models.IntegerField(default=0)),
                ("touchbacks", models.IntegerField(default=0)),
                ("inside_20", models.IntegerField(default=0)),
                ("out_of_bounds", models.IntegerField(default=0)),
                ("to_endzone", models.IntegerField(default=0)),
                ("return_yards", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PassingBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("attempts", models.IntegerField(default=0)),
                ("completions", models.IntegerField(default=0)),
                ("completion_pct", models.FloatField(blank=True, null=True)),
                ("yards", models.IntegerField(default=0)),
                ("yards_per_attempt", models.FloatField(blank=True, null=True)),
                ("touchdowns", models.IntegerField(default=0)),
                ("interceptions", models.IntegerField(default=0)),
                ("sacks", models.IntegerField(default=0)),
                ("sack_yards", models.IntegerField(default=0)),
                ("qb_rating", models.FloatField(blank=True, null=True)),
                ("longest_pass", models.IntegerField(blank=True, null=True)),
                ("longest_td_pass", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("play_id", models.IntegerField()),
                ("sequence", models.FloatField()),
                ("quarter", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("down", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "yards_to_go",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("play_type", models.CharField(blank=True, default="", max_length=40)),
                ("play_description", models.TextField(blank=True, default="")),
                ("play_state", models.CharField(blank=True, default="", max_length=20)),
                ("home_score", models.PositiveSmallIntegerField(default=0)),
                ("visitor_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "yard_line_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "yard_line_side",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("is_scoring", models.BooleanField(default=False)),
                ("is_big_play", models.BooleanField(default=False)),
                ("is_stp_play", models.BooleanField(default=False)),
                ("is_marker_play", models.BooleanField(default=False)),
                ("is_red_zone_play", models.BooleanField(blank=True, null=True)),
                (
                    "start_game_clock",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "end_game_clock",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("ngs_data", models.JSONField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="archive.game",
                    ),
                ),
                (
                    "possession_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="archive.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PlayStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("team_abbr", models.CharField(blank=True, default="", max_length=5)),
                (
                    "player_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("gsis_id", models.CharField(blank=True, default="", max_length=20)),
                ("stat_id", models.IntegerField()),
                ("yards", models.IntegerField(default=0)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="archive.play",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PuntingBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("attempts", models.IntegerField(default=0)),
                ("yards", models.IntegerField(default=0)),
                ("gross_avg", models.FloatField(blank=True, null=True)),
                ("net_avg", models.FloatField(blank=True, null=True)),
                ("blocked", models.IntegerField(default=0)),
                ("longest", models.IntegerField(blank=True, null=True)),
                ("touchbacks", models.IntegerField(default=0)),
                ("inside_20", models.IntegerField(default=0)),
                ("return_yards", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuarterScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("period", models.PositiveSmallIntegerField()),
                ("points", models.PositiveSmallIntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarter_scores",
                        to="archive.game",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "ordering": ["game", "team", "period"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("receptions", models.IntegerField(default=0)),
                ("yards", models.IntegerField(default=0)),
                ("avg_yards", models.FloatField(blank=True, null=True)),
                ("touchdowns", models.IntegerField(default=0)),
                ("targets", models.IntegerField(blank=True, null=True)),
                ("longest_reception", models.IntegerField(blank=True, null=True)),
                ("longest_td_reception", models.IntegerField(blank=True, null=True)),
                ("yards_after_catch", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("return_type", models.CharField(max_length=12)),
                ("returns", models.IntegerField(default=0)),
                ("yards", models.IntegerField(default=0)),
                ("avg_yards", models.FloatField(blank=True, null=True)),
                ("touchdowns", models.IntegerField(default=0)),
                ("longest", models.IntegerField(blank=True, null=True)),
                ("longest_td", models.IntegerField(blank=True, null=True)),
                ("fair_catches", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RushingBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("attempts", models.IntegerField(default=0)),
                ("yards", models.IntegerField(default=0)),
                ("avg_yards", models.FloatField(blank=True, null=True)),
                ("touchdowns", models.IntegerField(default=0)),
                ("longest_rush", models.IntegerField(blank=True, null=True)),
                ("longest_td_rush", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TacklesBoxscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("side", models.CharField(max_length=4)),
                ("player_name", models.CharField(max_length=120)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                ("tackles", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("sacks", models.FloatField(default=0)),
                ("sack_yards", models.IntegerField(default=0)),
                ("qb_hits", models.IntegerField(default=0)),
                ("tackles_for_loss", models.IntegerField(default=0)),
                ("tackles_for_loss_yards", models.IntegerField(default=0)),
                ("safeties", models.IntegerField(default=0)),
                ("special_teams_tackles", models.IntegerField(default=0)),
                ("special_teams_assists", models.IntegerField(default=0)),
                ("special_teams_blocks", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="archive.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamStandingsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("week", models.PositiveSmallIntegerField()),
                ("overall_wins", models.PositiveSmallIntegerField(default=0)),
                ("overall_losses", models.PositiveSmallIntegerField(default=0)),
                ("overall_ties", models.PositiveSmallIntegerField(default=0)),
                ("overall_win_pct", models.FloatField(default=0.0)),
                ("points_for", models.PositiveIntegerField(default=0)),
                ("points_against", models.PositiveIntegerField(default=0)),
                ("conference_wins", models.PositiveSmallIntegerField(default=0)),
                ("conference_losses", models.PositiveSmallIntegerField(default=0)),
                (
                    "conference_rank",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("division_wins", models.PositiveSmallIntegerField(default=0)),
                ("division_losses", models.PositiveSmallIntegerField(default=0)),
                (
                    "division_rank",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("home_wins", models.PositiveSmallIntegerField(default=0)),
                ("home_losses", models.PositiveSmallIntegerField(default=0)),
                ("road_wins", models.PositiveSmallIntegerField(default=0)),
                ("road_losses", models.PositiveSmallIntegerField(default=0)),
                ("streak_length", models.PositiveSmallIntegerField(default=0)),
                ("streak_type", models.CharField(blank=True, default="", max_length=1)),
                ("clinched_playoff", models.BooleanField(default=False)),
                ("clinched_division", models.BooleanField(default=False)),
                ("clinched_bye", models.BooleanField(default=False)),
                ("eliminated", models.BooleanField(default=False)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standings_snapshots",
                        to="archive.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standings_snapshots",
                        to="archive.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "started_quarter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "started_clock",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "started_description",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "started_yard_line",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "ended_quarter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ended_clock", models.CharField(blank=True, default="", max_length=8)),
                (
                    "ended_description",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "ended_yard_line",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("ended_with_score", models.BooleanField(default=False)),
                ("plays_count", models.PositiveSmallIntegerField(default=0)),
                ("first_downs", models.PositiveSmallIntegerField(default=0)),
                ("yards_gained", models.IntegerField(default=0)),
                ("yards_gained_net", models.IntegerField(default=0)),
                ("yards_gained_by_penalty", models.IntegerField(default=0)),
                (
                    "time_of_possession",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("inside_20", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drives",
                        to="archive.game",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="archive.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "sequence"), name="uniq_drive_game_seq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GameReplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                (
                    "replay_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("sub_type", models.CharField(blank=True, default="", max_length=80)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "mcp_playback_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replays",
                        to="archive.game",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["game", "sub_type"],
                        name="archive_gam_game_id_5642d2_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["game", "sequence"], name="archive_pla_game_id_401e85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["game", "quarter"], name="archive_pla_game_id_1c7032_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="play",
            constraint=models.UniqueConstraint(
                fields=("game", "play_id"), name="uniq_play_game_playid"
            ),
        ),
        migrations.AddConstraint(
            model_name="quarterscore",
            constraint=models.UniqueConstraint(
                fields=("game", "team", "period"), name="uniq_quarter_score"
            ),
        ),
        migrations.AddIndex(
            model_name="teamstandingssnapshot",
            index=models.Index(
                fields=["season", "week"], name="archive_tea_season__73d5e0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamstandingssnapshot",
            constraint=models.UniqueConstraint(
                fields=("team", "season", "week"), name="uniq_standings_snapshot"
            ),
        ),
    ]
