# Generated by Django 6.0.1 on 2026-02-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archive",
            "0020_game_broadcast_channel_game_kickoff_utc_game_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamereplay",
            name="title",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
