# Generated by Django 6.0.1 on 2026-02-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0021_alter_gamereplay_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamereplay",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
