# Generated by Django 6.0.1 on 2026-02-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0022_alter_gamereplay_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="era_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="era_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_data",
                    models.JSONField(
                        help_text="Data supplied by third party providers that we haven't decided how or if to use yet.",
                        null=True,
                    ),
                ),
                ("external_ids", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=160)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="franchises",
                        to="archive.league",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "franchises",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="archive.franchise",
            ),
        ),
        migrations.AddConstraint(
            model_name="franchise",
            constraint=models.UniqueConstraint(
                fields=("league", "name"), name="uniq_franchise_league_name"
            ),
        ),
    ]
