name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: ./.github/actions/setup-python-ci-env
        with:
          aws-role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          codeartifact-domain: ${{ secrets.AWS_CODEARTIFACT_DOMAIN }}
          codeartifact-domain-owner: ${{ secrets.AWS_ACCOUNT_ID }}
      - name: Install deps
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest
        env:
          DJANGO_SETTINGS_MODULE: gam.settings_ci