# Generated by Django 6.0.1 on 2026-04-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gam_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label (e.g. 'CI server', 'Local dev').",
                        max_length=255,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("live", "Live"), ("test", "Test")],
                        default="live",
                        max_length=8,
                    ),
                ),
                ("key_prefix", models.CharField(db_index=True, max_length=24)),
                ("key_hash", models.CharField(max_length=128)),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Permission strings using the same catalog as JWT tokens (e.g. ['catalog:read']).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="gam_accounts.clerkaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "ordering": ("-created_at",),
            },
        ),
    ]
